/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) hvac_dyn_disc_phi_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {3, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};
static const casadi_int casadi_s2[3] = {4, 3, 1};

/* hvac_dyn_disc_phi_fun_jac:(i0[3],i1,i2[3])->(o0[3],o1[4x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16;
  a00=9.3400168232027303e-01;
  a01=arg[0]? arg[0][0] : 0;
  a02=(a00*a01);
  a03=4.3230629776481698e-02;
  a04=arg[0]? arg[0][1] : 0;
  a05=(a03*a04);
  a02=(a02+a05);
  a05=2.2725742581677130e-02;
  a06=arg[0]? arg[0][2] : 0;
  a07=(a05*a06);
  a02=(a02+a07);
  a07=6.3478490700776383e-07;
  a08=arg[1]? arg[1][0] : 0;
  a09=(a07*a08);
  a02=(a02+a09);
  a09=4.1945321568137650e-05;
  a10=arg[2]? arg[2][0] : 0;
  a09=(a09*a10);
  a11=7.8883554694358026e-04;
  a12=arg[2]? arg[2][1] : 0;
  a11=(a11*a12);
  a09=(a09+a11);
  a02=(a02+a09);
  if (res[0]!=0) res[0][0]=a02;
  a02=6.1354492468661787e-02;
  a09=(a02*a01);
  a11=9.3790548245033345e-01;
  a13=(a11*a04);
  a09=(a09+a13);
  a13=7.3911656182152079e-04;
  a14=(a13*a06);
  a09=(a09+a14);
  a14=2.7807579876679633e-05;
  a15=(a14*a08);
  a09=(a09+a15);
  a15=9.0851918323867301e-07;
  a15=(a15*a10);
  a16=2.5609845694102578e-05;
  a16=(a16*a12);
  a15=(a15+a16);
  a09=(a09+a15);
  if (res[0]!=0) res[0][1]=a09;
  a09=6.6713386455918974e-03;
  a01=(a09*a01);
  a15=1.5288082996603911e-04;
  a04=(a15*a04);
  a01=(a01+a04);
  a04=9.8955156741569028e-01;
  a06=(a04*a06);
  a01=(a01+a06);
  a06=1.4811351048068123e-09;
  a08=(a06*a08);
  a01=(a01+a08);
  a08=3.6242131087517804e-03;
  a08=(a08*a10);
  a10=2.7588270233757485e-06;
  a10=(a10*a12);
  a08=(a08+a10);
  a01=(a01+a08);
  if (res[0]!=0) res[0][2]=a01;
  if (res[1]!=0) res[1][0]=a07;
  if (res[1]!=0) res[1][1]=a00;
  if (res[1]!=0) res[1][2]=a03;
  if (res[1]!=0) res[1][3]=a05;
  if (res[1]!=0) res[1][4]=a14;
  if (res[1]!=0) res[1][5]=a02;
  if (res[1]!=0) res[1][6]=a11;
  if (res[1]!=0) res[1][7]=a13;
  if (res[1]!=0) res[1][8]=a06;
  if (res[1]!=0) res[1][9]=a09;
  if (res[1]!=0) res[1][10]=a15;
  if (res[1]!=0) res[1][11]=a04;
  return 0;
}

CASADI_SYMBOL_EXPORT int hvac_dyn_disc_phi_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int hvac_dyn_disc_phi_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int hvac_dyn_disc_phi_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hvac_dyn_disc_phi_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int hvac_dyn_disc_phi_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hvac_dyn_disc_phi_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void hvac_dyn_disc_phi_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void hvac_dyn_disc_phi_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int hvac_dyn_disc_phi_fun_jac_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int hvac_dyn_disc_phi_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real hvac_dyn_disc_phi_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hvac_dyn_disc_phi_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hvac_dyn_disc_phi_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hvac_dyn_disc_phi_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hvac_dyn_disc_phi_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int hvac_dyn_disc_phi_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int hvac_dyn_disc_phi_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
