/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) hvac_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {3, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};

/* hvac_dyn_disc_phi_fun:(i0[3],i1,i2[3])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
  a0=9.3400168232027303e-01;
  a1=arg[0]? arg[0][0] : 0;
  a0=(a0*a1);
  a2=4.3230629776481698e-02;
  a3=arg[0]? arg[0][1] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=2.2725742581677130e-02;
  a4=arg[0]? arg[0][2] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=6.3478490700776383e-07;
  a5=arg[1]? arg[1][0] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=4.1945321568137650e-05;
  a6=arg[2]? arg[2][0] : 0;
  a2=(a2*a6);
  a7=7.8883554694358026e-04;
  a8=arg[2]? arg[2][1] : 0;
  a7=(a7*a8);
  a2=(a2+a7);
  a0=(a0+a2);
  if (res[0]!=0) res[0][0]=a0;
  a0=6.1354492468661787e-02;
  a0=(a0*a1);
  a2=9.3790548245033345e-01;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=7.3911656182152079e-04;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=2.7807579876679633e-05;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=9.0851918323867301e-07;
  a2=(a2*a6);
  a7=2.5609845694102578e-05;
  a7=(a7*a8);
  a2=(a2+a7);
  a0=(a0+a2);
  if (res[0]!=0) res[0][1]=a0;
  a0=6.6713386455918974e-03;
  a0=(a0*a1);
  a1=1.5288082996603911e-04;
  a1=(a1*a3);
  a0=(a0+a1);
  a1=9.8955156741569028e-01;
  a1=(a1*a4);
  a0=(a0+a1);
  a1=1.4811351048068123e-09;
  a1=(a1*a5);
  a0=(a0+a1);
  a1=3.6242131087517804e-03;
  a1=(a1*a6);
  a6=2.7588270233757485e-06;
  a6=(a6*a8);
  a1=(a1+a6);
  a0=(a0+a1);
  if (res[0]!=0) res[0][2]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int hvac_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int hvac_dyn_disc_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int hvac_dyn_disc_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hvac_dyn_disc_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int hvac_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hvac_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void hvac_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void hvac_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int hvac_dyn_disc_phi_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int hvac_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real hvac_dyn_disc_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hvac_dyn_disc_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hvac_dyn_disc_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hvac_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hvac_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int hvac_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int hvac_dyn_disc_phi_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
